name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Docker images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - { name: "app", path: "./app" }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image (Test Only)
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.image.path }}
          file: ${{ matrix.image.path }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
